export const PORTFOLIO = {

  meta: {
    name:             "Karim Ayman",
    fullName:         "Karim Ayman Fawzy",
    shortName:        "K",
    title:            "Full Stack Developer — ASP.NET Core · React.js · AI-Assisted Development",
    tagline:          "I don't stop at the frontend.",
    subtitle:         "ASP.NET Core · React.js · SQL Server · Entity Framework · REST APIs",
    bio:              "I architect the database, build the API, and own the UI — end to end, clean architecture throughout. Led a 6-person team delivering a production dual-platform system. Delivered backend and frontend for 2 paid clients. Currently teaching 50+ students full-stack development at iSchool.",
    targetRoles:      "Open to remote · Open to R&D roles",
    email:            "Kareem.apple1111@gmail.com",
    phone:            "01142391819",
    location:         "Mansoura, Egypt",
    cvUrl:            "https://drive.google.com/drive/folders/116D1ChyeWawX3--9KNdXaYFP5CFX0abt?usp=sharing",
    availableForHire: true,
    profileImage:     "./images/MyPecs-800.webp",
    copyrightYear:    new Date().getFullYear(),
    stats: [
      { value: "50+",   label: "Students Taught"      },
      { value: "2",     label: "Freelance Clients"     },
      { value: "4 yrs", label: "Experience"            },
      { value: "30+",   label: "API Endpoints Per App" },
      { value: "3",     label: "Platforms Shipped"     },
    ],
  },

  seo: {
    description:   "Full Stack Developer specializing in ASP.NET Core and React.js. Based in Mansoura, Egypt. Available for remote opportunities.",
    keywords:      "Full Stack Developer, React Developer, .NET Developer, ASP.NET Core, Web Developer, JavaScript, C#, Karim Ayman, Egypt Developer, Remote Developer, Mansoura",
    ogImage:       "https://karimmayman.github.io/KarimAyman.dev/images/MyPecs-800.webp",
    twitterHandle: "@karrim_ayman",
    canonicalUrl:  "https://karimmayman.github.io/KarimAyman.dev/",
    siteName:      "Karim Ayman Portfolio",
    locale:        "en_US",
  },

  social: [
    { platform: "github",    label: "GitHub",    url: "https://github.com/KarimmAyman",                icon: "fab fa-github"    },
    { platform: "linkedin",  label: "LinkedIn",  url: "https://www.linkedin.com/in/karim-ayman-fawzy", icon: "fab fa-linkedin"  },
    { platform: "instagram", label: "Instagram", url: "https://www.instagram.com/karrim_ayman/",       icon: "fab fa-instagram" },
    { platform: "facebook",  label: "Facebook",  url: "https://www.facebook.com/kareem.elmoghier",     icon: "fab fa-facebook"  },
  ],

  // Each skill is { name, icon } — icon = Font Awesome class string.
  // Add a skill → append { name, icon } to the array.
  // Add a category → add a new key.
  skills: {
    Backend: [
      { name: "ASP.NET Core",   icon: "fas fa-server"        },
      { name: "Web API",        icon: "fas fa-plug"           },
      { name: "C#",             icon: "fas fa-code"           },
      { name: "MVC",            icon: "fas fa-layer-group"    },
      { name: "Entity Framework Core", icon: "fas fa-database"},
      { name: "LINQ",           icon: "fas fa-filter"         },
      { name: "JWT Auth",       icon: "fas fa-key"            },
      { name: "RESTful API",    icon: "fas fa-exchange-alt"   },
      { name: "Laravel (PHP)",  icon: "fab fa-laravel"        },
      { name: "Express.js",     icon: "fab fa-node-js"        },
    ],
    Frontend: [
      { name: "React.js",       icon: "fab fa-react"          },
      { name: "Tailwind CSS",   icon: "fas fa-wind"           },
      { name: "Bootstrap",      icon: "fab fa-bootstrap"      },
      { name: "JavaScript ES6+",icon: "fab fa-js"             },
      { name: "HTML5 / CSS3",   icon: "fab fa-html5"          },
      { name: "Figma",          icon: "fab fa-figma"          },
      { name: "Blade (Laravel)",icon: "fas fa-file-code"      },
    ],
    "Data & Tools": [
      { name: "SQL Server",     icon: "fas fa-database"       },
      { name: "MySQL",          icon: "fas fa-database"       },
      { name: "Supabase",       icon: "fas fa-bolt"           },
      { name: "Git / GitHub",   icon: "fab fa-git-alt"        },
      { name: "Swagger / OpenAPI", icon: "fas fa-file-alt"    },
      { name: "Postman",        icon: "fas fa-paper-plane"    },
      { name: "Visual Studio",  icon: "fas fa-laptop-code"    },
      { name: "VS Code",        icon: "fas fa-code"           },
    ],
    Mobile: [
      { name: "Flutter UI (AI-assisted)", icon: "fas fa-mobile-alt" },
    ],
    "AI & Prompting": [
      { name: "GitHub Copilot", icon: "fab fa-github"         },
      { name: "ChatGPT",        icon: "fas fa-robot"          },
      { name: "Claude",         icon: "fas fa-brain"          },
      { name: "Gemini",         icon: "fas fa-star"           },
    ],
  },

  // type: "work" | "education" — controls icon rendered in timeline
  experience: [
    {
      type:        "work",
      period:      "Jan 2025 – Present",
      role:        "Backend & Frontend Developer (Freelance)",
      company:     "Goia · Remote",
      description: "Designed and implemented RESTful APIs for floor-plan management, anchor points, and user sessions using Express.js and Supabase — consumed by both a React.js web admin panel and Flutter mobile app. Delivered the Flutter mobile UI via AI-assisted development (Claude, Antigravity) across 7 milestone phases: screen flows, sensor display, and real-time PDR navigation map.",
      tech:        ["Express.js", "Supabase", "React.js", "Flutter", "Claude", "Antigravity"],
    },
    {
      type:        "work",
      period:      "2025 – Present",
      role:        "Web Development Instructor",
      company:     "iSchool · Remote",
      description: "Teaching full-stack web development to 30–50 students per cohort — HTML, CSS, JavaScript, React.js, hooks, state management, and Tailwind CSS through to a shipped capstone app. Designed project-based curriculum; mentors students on clean code, debugging, and Git workflows.",
      tech:        ["React.js", "JavaScript", "HTML/CSS", "Tailwind CSS"],
    },
    {
      type:        "work",
      period:      "Jan 2025 – Present",
      role:        "STEM Instructor & Backend Developer",
      company:     "Techno Square · Mansoura, Egypt",
      description: "Taught Web Development, Arduino, and AI to 30–50 students aged 12+, delivering projects including a Hand Gesture-Controlled Car and Smart Parking System. Extended a live Laravel backend with new REST API endpoints and a Blade-templated site using AI-assisted PHP.",
      tech:        ["Laravel", "PHP", "Arduino", "AI Tools"],
    },
    {
      type:        "education",
      period:      "2021 – 2025",
      role:        "B.Sc. Computer and Information Sciences",
      company:     "Kafr El-Sheikh University",
      description: "Graduated with a GPA of 3.5 / 4.0.",
    },
  ],

  certifications: [
    { issuer: "ITI (150 hrs · Frontend track)",  detail: "HTML, CSS, JavaScript, React.js, Tailwind CSS, Bootstrap — Audiophile e-commerce capstone" },
    { issuer: "DEPI (.NET backend track)",        detail: "Online Quiz Platform delivered as team project" },
  ],

  projects: [
    {
      id:          "aoun",
      title:       "Aoun Platform — Integrated Student Services",
      label:       "GRADUATION PROJECT",
      tags:        ["Mobile", "Transportation", "Web", "Housing"],
      image:       "./images/Aoun-800.webp",
      role:        "Team Leader & Backend Developer · Team of 6",
      description: "Led a 6-person backend team building ASP.NET Core Web API with JWT authentication, role-based access control (student / driver / admin), and three core modules using Entity Framework Core with full Swagger documentation. Managed Git branching and Agile sprint planning. Web Platform (React.js + Vite): Housing management and student opportunities. Mobile App (Flutter): Transportation system with Google Maps, offline support via Hive, and BLoC state management. Payments: Stripe & Paymob.",
      tech:        ["ASP.NET Core", "Entity Framework Core", "JWT", "Swagger", "React.js", "Vite", "Axios", "Flutter", "BLoC", "Hive", "Google Maps", "Stripe", "Paymob", "SQL Server"],
      links: [
        { label: "View Code", url: "https://github.com/KarimmAyman/StudentPathProject", icon: "fab fa-github" },
      ],
      videos: [
        { label: "Auth Flow",      file: "./AounVideos/AppAuth.mp4",             emoji: "🔐" },
        { label: "Driver Flow",    file: "./AounVideos/DriverAuth.mp4",          emoji: "🚗" },
        { label: "Passenger Flow", file: "./AounVideos/PassengerFlow-ezgif.mp4", emoji: "👨🎓" },
        { label: "Web Promo",      file: "./AounVideos/webPromo.mp4",            emoji: "🌐" },
      ],
      featured: true,

      // Aoun-specific detail showcase section data
      // Rendered as the full "Complete Technical Showcase" section below the project cards
      details: {
        platforms: [
          { label: "Flutter App",   sub: "Transportation",    icon: "fas fa-mobile-alt" },
          { label: "React.js Web",  sub: "Housing & Events",  icon: "fab fa-react"      },
          { label: "One Goal",      sub: "Student Life",      icon: "fas fa-graduation-cap" },
        ],
        highlights: [
          { title: "Authentication & Authorization",  body: "JWT-based auth with role-based access control across web and mobile (student / driver / admin)." },
          { title: "Driver Flow (Flutter)",           body: "Real-time GPS tracking, route optimization with Google Maps API, and offline data with Hive." },
          { title: "Passenger Flow (Flutter)",        body: "Transportation booking, trip tracking, payment integration (Stripe & Paymob), and BLoC state management." },
          { title: "Web Platform (React.js)",         body: "Housing management, student opportunities, event registration built with React.js + Vite and Axios API integration." },
        ],
        myRole: "Team Leader & Backend Developer",
        myRoleSummary: "Led backend development and built the complete React web application",
        backendModules: [
          "Authentication System — JWT auth with role-based authorization (4 user roles)",
          "Student Housing Module — complete API for requests, applications, and management",
          "Activities Management — endpoints for campus events, workshops, and student registration",
          "Driver Registration — API for driver management and verification system",
          "RESTful Design — clean architecture with Entity Framework Core and SQL Server",
        ],
        webModules: [
          "Authentication UI — login, registration, and secure session management with JWT tokens",
          "Housing Portal — browse housing options, submit applications, track request status",
          "Activities & Events — view campus events, register for workshops, manage bookings",
          "Axios Integration — configured HTTP client with interceptors for secure API communication",
          "Responsive Design — mobile-first UI with dark mode, built with Tailwind CSS",
        ],
        ecosystem: [
          { label: "Backend Modules",    owner: "My Work",  stack: "ASP.NET Core · SQL Server · JWT · EF Core",        summary: "Authentication, Student Housing, Activities Management, and Driver Registration APIs" },
          { label: "Web Platform",       owner: "My Work",  stack: "React.js · Vite · Axios · Tailwind CSS",           summary: "Complete student portal with authentication, housing requests, and events management" },
          { label: "Additional Features",owner: "Team",     stack: "Flutter · Payment Gateways · Google Maps",         summary: "Mobile app, transportation system, and payment integrations (developed by team members)" },
        ],
        tools: [
          { name: "Visual Studio", sub: "ASP.NET Core backend", icon: "fas fa-laptop-code"  },
          { name: "VS Code",       sub: "React development",    icon: "fas fa-code"          },
          { name: "GitHub",        sub: "Version control",      icon: "fab fa-github"        },
          { name: "Postman",       sub: "API testing",          icon: "fas fa-paper-plane"   },
          { name: "SSMS",          sub: "Database management",  icon: "fas fa-database"      },
          { name: "Swagger",       sub: "API docs",             icon: "fas fa-file-alt"      },
        ],
        leadership: [
          "Led backend development team for the project",
          "Coordinated between backend, web, and mobile development teams",
          "Managed agile sprints using GitHub for version control",
          "Conducted code reviews and maintained technical documentation",
        ],
        achievements: [
          "Built secure JWT authentication with role-based access control",
          "Developed Student Housing module with complete CRUD operations",
          "Created Activities Management system for campus events",
          "Implemented Driver Registration API with verification flow",
          "Integrated Axios for seamless React-API communication",
        ],
        stats: [
          { value: "3",     label: "Core Modules",    sub: "Housing, Activities, Auth" },
          { value: "JWT",   label: "Authentication",  sub: "Role-Based Access"         },
          { value: "React", label: "Web Platform",    sub: "Full Frontend"             },
          { value: "100%",  label: "Responsive",      sub: "Mobile-First"              },
        ],
      },
    },
    {
      id:          "goia",
      title:       "Goia — Indoor Navigation Platform",
      label:       "FREELANCE",
      tags:        ["Express.js", "Supabase", "Flutter", "React.js"],
      image:       null,
      role:        "Backend & Frontend Developer",
      description: "Designed and implemented RESTful APIs for floor-plan management, anchor points, and user sessions using Express.js and Supabase — consumed by a React.js web admin panel and Flutter mobile app. Delivered the Flutter UI via AI-assisted development (Claude, Antigravity) across 7 milestone phases: screen flows, sensor display, and real-time PDR navigation map.",
      tech:        ["Express.js", "Supabase", "React.js", "Flutter", "Claude", "Antigravity"],
      links:       [],
      videos:      [],
      featured:    false,
    },
    {
      id:          "quiz",
      title:       "Online Quiz Platform",
      label:       "QUIZ MASTER",
      tags:        ["Full-Stack", "MVC", "API"],
      image:       "./images/onlineQuiz-800.webp",
      role:        "Backend Developer · DEPI Team Project",
      description: "Built quiz and question modules using ASP.NET Core Web API with Generic Repository Pattern, JWT auth, randomized question delivery, timer functionality, score tracking, and instructor progress dashboards.",
      tech:        ["ASP.NET Core", "Web API", "Generic Repository Pattern", "Entity Framework", "JWT"],
      links: [
        { label: "MVC App",  url: "https://quizmasterplatform.runasp.net/",    icon: "fas fa-external-link-alt" },
        { label: "API Docs", url: "https://quizmasterplatformapi.runasp.net/", icon: "fas fa-file-alt"          },
      ],
      videos:   [],
      featured: false,
    },
    {
      id:          "audiophile",
      title:       "Audiophile E-Commerce",
      label:       "AUDIOPHILE",
      tags:        ["Premium Audio", "React.js"],
      image:       "./images/AudioPhile-800.webp",
      role:        "Frontend Developer · ITI Capstone",
      description: "Fully responsive storefront in React.js and Tailwind CSS from Figma wireframes — authentication, cart management, checkout, and .NET REST API integration.",
      tech:        ["React.js", "Tailwind CSS", "Figma", "Context API", ".NET REST API"],
      links: [
        { label: "View Live Demo", url: "https://audiophiles-e-commerce-app.vercel.app/", icon: "fas fa-external-link-alt" },
      ],
      videos:   [],
      featured: false,
    },
    {
      id:          "maona",
      title:       "Maona Trading Company",
      label:       "MAONA",
      tags:        ["Food Distribution", "Saudi Arabia"],
      image:       "./images/web2-800.webp",
      role:        null,
      description: "Professional business website for Saudi Arabia's leading food distribution company. Showcases multiple product categories and international brands (Mama Sauce, Makin, Top Top, Lutosa, Crinkle Cook, Cavendish, Jordina). Fully responsive design built with modern frontend technologies.",
      tech:        ["HTML5", "Tailwind CSS", "JavaScript", "Responsive"],
      links: [
        { label: "View Live Demo", url: "https://karimmayman.github.io/maounahNew/", icon: "fas fa-external-link-alt" },
      ],
      videos:   [],
      featured: false,
    },
  ],
};
